### ISSUE TITLE
Learn IDE fails to launch when clicking on "open" in the lessons

### ISSUE THREAD

**Issue by dlbooker** [learn-co-curriculum/javascript-logging-lab#18]

**Comment by AnnJohn** [comment]
hi @dlbooker sorry for the issue that you're having. Since this is a product issue, could you file a bug report (if you click on your profile pic in Learn, you'll see a menu with an option to 'Report a Bug') and use Ask a Question so that someone from our team can help you out right away. 

We use this space specifically for issues related to the content in the curriculum. Thanks!
