### ISSUE TITLE
Cannot find javascript logging lab exercise in IDE

### ISSUE THREAD

**Issue by Afromarine** [learn-co-curriculum/javascript-logging-lab#34]
I clicked on the open page to start my IDE and cannot find the javascript logging folder to start or complete the lesson. I asked for assistance on the site but it is still not there. What should I do? 

![screen shot 2016-10-04 at 5 22 46 pm](https://cloud.githubusercontent.com/assets/22620321/19093177/1133c558-8a58-11e6-946c-7b235b1264d7.png)

**Comment by aturkewi** [comment]
This isn't really the best place to raise this question as it's more of an issue with the IDE than the lab. The best place for this kind of thing is the Ask A Question button in Learn.co

Specifically though, it looks like your IDE is double typing the name of the lab and that's why the `learn open` command cannot find it. Check out this help center article: https://help.learn.co/hc/en-us/articles/236271127-Text-Doubling-in-the-Learn-IDE

If you still need a hand, try the Ask A Question button on Learn :)
