### ISSUE TITLE
click on the open button and nothing happens

### ISSUE THREAD

**Issue by amadanes** [learn-co-curriculum/javascript-logging-lab#35]

**Comment by ellalaviolette** [comment]
same thing is happening to me.

**Comment by aturkewi** [comment]
Hey @amadanes and @ellalaviolette this isn't really the best place for this kinds of problems because those are more related to the site and the IDE, but not to this lab specifically. The best place to ask those questions is the Ask A Question button on Learn.co. 

Also, check out this help center article about open button issues: https://help.learn.co/hc/en-us/articles/230234808--Learn-open-button-issues

If you still need a hand after reading that, try the Ask A Question button :)
