### ISSUE TITLE
Javascript Logging Lab issue

### ISSUE THREAD

**Issue by vientang** [learn-co-curriculum/javascript-logging-lab#39]
All three console (log, warn, error) functions were printed and tests passed however the next lesson button is not active. Here's a screenshot. 
<img width="1269" alt="screen shot 2016-11-30 at 1 09 05 pm" src="https://cloud.githubusercontent.com/assets/8237124/20771447/46928c52-b6fe-11e6-9dd8-d98489471b21.png">

**Comment by aturkewi** [comment]
@vientang the best place to get help with something like this would be Ask A Question rather than raising an issue with the lab. 
If you take a look at the screen shot though, you only have 2 of the three lights needed to proceed. The one you're missing is the Submit light. Take a look at this section of the [ReadMe](https://github.com/learn-co-curriculum/javascript-logging-lab/blob/master/README.md#your-turn) I think you'll find that you've missed the step where you `learn submit`
